#mainly for vm
version: '3.3'
services:
  # #frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_API_URL=http://localhost:3000
  #   depends_on:
  #     - backend

  #backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

#v1
# docker-compose up --build -d backend 

#v2
# docker compose up --build -d backend

#heath check
# docker ps

#logs
# docker logs behaviorai-backend-1 -f

#usage
# docker stats 
